import { createClient } from "@supabase/supabase-js"
import { notFound } from "next/navigation"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

export default async function SharedReportPage({ params }: { params: { token: string } }) {
  const { data: report } = await supabase
    .from("pulse_reports")
    .select("*")
    .eq("share_token", params.token)
    .eq("is_public", true)
    .single()

  if (!report) return notFound()

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-6 py-8">
        <div className="flex items-center justify-between mb-8 pb-6 border-b border-gray-200">
          <div className="text-xl font-black text-gray-900">KLARO <span className="text-indigo-600">PULSE</span></div>
          <div className="text-sm text-gray-500">{new Date(report.created_at).toLocaleDateString("en-US",{day:"numeric",month:"long",year:"numeric"})}</div>
        </div>
        <div dangerouslySetInnerHTML={{ __html: report.report_html }} />
        <div className="mt-8 pt-6 border-t border-gray-200 text-center">
          <p className="text-sm text-gray-400">Generated by <a href="https://klaro.services/pulse" className="text-indigo-600 hover:underline">Klaro Pulse</a> · AI-powered site intelligence</p>
        </div>
      </div>
    </div>
  )
}
